### ISSUE TITLE
Error when building with Visual Studio

### ISSUE THREAD

**Issue by seb-jones** [ashinn/chibi-scheme#632]
I clone the repo, right-click the folder in File Explorer and choose 'Open in Visual Studio', and click 'CMake > Build All' (so using the default x64-Debug configuration), and it fails on the following error:

```
C:\Users\Seb\Downloads\chibi-scheme-master\gc.c(522): error C2105: '++' needs l-value
```

This seems to happen no matter which configuration I choose.

**Comment by ashinn** [comment]
Should be fixed.

**Comment by seb-jones** [comment]
Still getting the same error with this. The problem appears to be that the `sexp_context_gc_count` macro is expanding to `0`.

**Comment by ashinn** [comment]
Sorry, try now.

**Comment by seb-jones** [comment]
Looks like it's working now. Thanks!
