### ISSUE TITLE
documentation: dead links

### ISSUE THREAD

**Issue by kristianlm** [ashinn/chibi-scheme#726]
Hi,

DuckDuckGo takes me to http://synthcode.com/scheme/chibi

Without the trailing slash. This causes the links to the "standard modules" (eg [chibi app](http://synthcode.com/scheme/lib/chibi/app.html)) to yield 404 Not Found.

If I go to http://synthcode.com/scheme/chibi/ then everything works. Perhaps a simple redirect is in order here?

**Comment by ashinn** [comment]
Done.

**Comment by kristianlm** [comment]
That's still not working for me:

1. navigate to http://synthcode.com/scheme/chibi
2. fint "chibi weak" on the page
3. click that [link](http://synthcode.com/scheme/lib/chibi/weak.html)
4. => 404 Not found

**Comment by ashinn** [comment]
Why is duckduckgo generating these links anyway?  The official links all have the trailing /.  I shouldn't be responsible for rewriting every broken link out there :P
